import { Request, Response } from 'express';
import prisma from '../utils/prisma';

// ============================================
// CREATE COUPON (Admin)
// ============================================
export async function createCoupon(req: Request, res: Response) {
  try {
    const userId = (req as any).user.id;
    const {
      code,
      description,
      discountType,
      discountValue,
      minPurchase,
      maxDiscount,
      maxUses,
      maxUsesPerUser,
      isEliteOnly,
      expiresAt,
    } = req.body;

    if (!code || !discountValue) {
      return res.status(400).json({ error: 'code and discountValue are required' });
    }

    // Validate code format (uppercase, no spaces)
    const normalizedCode = code.toUpperCase().replace(/\s/g, '');

    // Check if code already exists
    const existing = await prisma.coupon.findUnique({ where: { code: normalizedCode } });
    if (existing) {
      return res.status(409).json({ error: 'Coupon code already exists' });
    }

    // Validate discount
    if (discountType === 'PERCENTAGE' && (discountValue < 1 || discountValue > 50)) {
      return res.status(400).json({ error: 'Percentage discount must be between 1% and 50%' });
    }

    if (discountType === 'FIXED' && discountValue <= 0) {
      return res.status(400).json({ error: 'Fixed discount must be greater than 0' });
    }

    const coupon = await prisma.coupon.create({
      data: {
        code: normalizedCode,
        description: description || null,
        discountType: discountType || 'FIXED',
        discountValue,
        minPurchase: minPurchase || null,
        maxDiscount: maxDiscount || null,
        maxUses: maxUses || null,
        maxUsesPerUser: maxUsesPerUser || 1,
        isEliteOnly: isEliteOnly || false,
        isAutoGenerated: false,
        expiresAt: expiresAt ? new Date(expiresAt) : null,
        rovexApproval: 'PENDING', // Always requires Rovex approval
        createdById: userId,
      },
    });

    res.status(201).json(coupon);
  } catch (error) {
    console.error('[Coupons] Error creating coupon:', error);
    res.status(500).json({ error: 'Failed to create coupon' });
  }
}

// ============================================
// LIST COUPONS (Admin)
// ============================================
export async function listCoupons(req: Request, res: Response) {
  try {
    const status = req.query.status as string;
    const where: any = {};

    if (status === 'active') {
      where.isActive = true;
      where.rovexApproval = 'APPROVED';
    } else if (status === 'pending') {
      where.rovexApproval = 'PENDING';
    } else if (status === 'expired') {
      where.OR = [
        { isActive: false },
        { expiresAt: { lt: new Date() } },
      ];
    }

    const coupons = await prisma.coupon.findMany({
      where,
      include: {
        _count: { select: { usages: true } },
      },
      orderBy: { createdAt: 'desc' },
    });

    res.json(coupons);
  } catch (error) {
    console.error('[Coupons] Error listing coupons:', error);
    res.status(500).json({ error: 'Failed to list coupons' });
  }
}

// ============================================
// VALIDATE COUPON (User - at checkout)
// ============================================
export async function validateCoupon(req: Request, res: Response) {
  try {
    const userId = (req as any).user.id;
    const { code, purchaseAmount } = req.body;

    if (!code) {
      return res.status(400).json({ error: 'Coupon code is required' });
    }

    const coupon = await prisma.coupon.findUnique({
      where: { code: code.toUpperCase() },
      include: {
        usages: { where: { userId } },
        _count: { select: { usages: true } },
      },
    });

    if (!coupon) {
      return res.status(404).json({ error: 'Cupom não encontrado', valid: false });
    }

    // Check if approved by Rovex
    if (coupon.rovexApproval !== 'APPROVED') {
      return res.status(400).json({ error: 'Cupom aguardando aprovação', valid: false });
    }

    // Check if active
    if (!coupon.isActive) {
      return res.status(400).json({ error: 'Cupom inativo', valid: false });
    }

    // Check expiry
    if (coupon.expiresAt && coupon.expiresAt < new Date()) {
      return res.status(400).json({ error: 'Cupom expirado', valid: false });
    }

    // Check max uses
    if (coupon.maxUses && coupon._count.usages >= coupon.maxUses) {
      return res.status(400).json({ error: 'Cupom esgotado', valid: false });
    }

    // Check per-user limit
    if (coupon.usages.length >= coupon.maxUsesPerUser) {
      return res.status(400).json({ error: 'Você já usou este cupom', valid: false });
    }

    // Check Elite-only
    if (coupon.isEliteOnly) {
      const user = await prisma.user.findUnique({
        where: { id: userId },
        select: { isElite: true },
      });
      if (!user?.isElite) {
        return res.status(403).json({ error: 'Cupom exclusivo para membros Elite', valid: false });
      }
    }

    // Check minimum purchase
    if (coupon.minPurchase && purchaseAmount && purchaseAmount < coupon.minPurchase) {
      return res.status(400).json({
        error: `Compra mínima de R$ ${coupon.minPurchase.toFixed(2)}`,
        valid: false,
      });
    }

    // Calculate discount
    let discount = 0;
    if (coupon.discountType === 'FIXED') {
      discount = coupon.discountValue;
    } else {
      discount = (purchaseAmount || 0) * (coupon.discountValue / 100);
      if (coupon.maxDiscount && discount > coupon.maxDiscount) {
        discount = coupon.maxDiscount;
      }
    }

    res.json({
      valid: true,
      coupon: {
        id: coupon.id,
        code: coupon.code,
        description: coupon.description,
        discountType: coupon.discountType,
        discountValue: coupon.discountValue,
        maxDiscount: coupon.maxDiscount,
        isEliteOnly: coupon.isEliteOnly,
      },
      calculatedDiscount: Math.round(discount * 100) / 100,
    });
  } catch (error) {
    console.error('[Coupons] Error validating coupon:', error);
    res.status(500).json({ error: 'Failed to validate coupon' });
  }
}

// ============================================
// APPLY COUPON (internal - called during purchase)
// ============================================
export async function applyCoupon(couponId: string, userId: string, orderId: string, discount: number) {
  try {
    await prisma.$transaction([
      prisma.couponUsage.create({
        data: {
          couponId,
          userId,
          orderId,
          discount,
        },
      }),
      prisma.coupon.update({
        where: { id: couponId },
        data: { usedCount: { increment: 1 } },
      }),
    ]);
    return true;
  } catch (error) {
    console.error('[Coupons] Error applying coupon:', error);
    return false;
  }
}

// ============================================
// UPDATE COUPON (Admin)
// ============================================
export async function updateCoupon(req: Request, res: Response) {
  try {
    const { id } = req.params;
    const updates = req.body;

    const coupon = await prisma.coupon.findUnique({ where: { id } });
    if (!coupon) {
      return res.status(404).json({ error: 'Coupon not found' });
    }

    const updated = await prisma.coupon.update({
      where: { id },
      data: {
        description: updates.description,
        isActive: updates.isActive,
        maxUses: updates.maxUses,
        maxUsesPerUser: updates.maxUsesPerUser,
        expiresAt: updates.expiresAt ? new Date(updates.expiresAt) : undefined,
      },
    });

    res.json(updated);
  } catch (error) {
    console.error('[Coupons] Error updating coupon:', error);
    res.status(500).json({ error: 'Failed to update coupon' });
  }
}

// ============================================
// DELETE COUPON (Admin)
// ============================================
export async function deleteCoupon(req: Request, res: Response) {
  try {
    const { id } = req.params;

    await prisma.coupon.delete({ where: { id } });
    res.json({ success: true });
  } catch (error) {
    console.error('[Coupons] Error deleting coupon:', error);
    res.status(500).json({ error: 'Failed to delete coupon' });
  }
}

// ============================================
// ROVEX APPROVAL ENDPOINTS
// ============================================
export async function getPendingCouponApprovals(req: Request, res: Response) {
  try {
    const coupons = await prisma.coupon.findMany({
      where: { rovexApproval: 'PENDING' },
      orderBy: { createdAt: 'desc' },
    });

    res.json(coupons);
  } catch (error) {
    console.error('[Coupons] Error getting pending approvals:', error);
    res.status(500).json({ error: 'Failed to get pending approvals' });
  }
}

export async function reviewCouponApproval(req: Request, res: Response) {
  try {
    const { id } = req.params;
    const { approved, reviewNote } = req.body;

    const coupon = await prisma.coupon.update({
      where: { id },
      data: {
        rovexApproval: approved ? 'APPROVED' : 'REJECTED',
        rovexReviewedAt: new Date(),
        rovexReviewNote: reviewNote || null,
      },
    });

    res.json(coupon);
  } catch (error) {
    console.error('[Coupons] Error reviewing approval:', error);
    res.status(500).json({ error: 'Failed to review coupon approval' });
  }
}

// ============================================
// GENERATE ELITE MONTHLY COUPON
// ============================================
export async function generateEliteCoupon(req: Request, res: Response) {
  try {
    const userId = (req as any).user.id;

    // Check if user is Elite
    const user = await prisma.user.findUnique({
      where: { id: userId },
      select: { isElite: true, name: true },
    });

    if (!user?.isElite) {
      return res.status(403).json({ error: 'Only Elite members can claim monthly coupons' });
    }

    // Check if already generated this month
    const now = new Date();
    const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);
    const monthEnd = new Date(now.getFullYear(), now.getMonth() + 1, 0, 23, 59, 59);

    const existingCoupon = await prisma.coupon.findFirst({
      where: {
        createdById: userId,
        isAutoGenerated: true,
        createdAt: { gte: monthStart, lte: monthEnd },
      },
    });

    if (existingCoupon) {
      return res.json({ coupon: existingCoupon, alreadyClaimed: true });
    }

    // Generate unique code
    const code = `ELITE-${userId.slice(0, 4).toUpperCase()}-${now.getMonth() + 1}${now.getFullYear().toString().slice(-2)}`;

    const coupon = await prisma.coupon.create({
      data: {
        code,
        description: `Cupom Elite mensal de ${user.name}`,
        discountType: 'FIXED',
        discountValue: 10, // R$10 fixo
        maxUses: 1,
        maxUsesPerUser: 1,
        isEliteOnly: false, // Anyone can use if they know the code
        isAutoGenerated: true,
        expiresAt: monthEnd,
        rovexApproval: 'APPROVED', // Auto-approved for Elite
        createdById: userId,
      },
    });

    res.json({ coupon, alreadyClaimed: false });
  } catch (error) {
    console.error('[Coupons] Error generating elite coupon:', error);
    res.status(500).json({ error: 'Failed to generate elite coupon' });
  }
}
