import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Tag, Plus, Trash2, CheckCircle, XCircle, Clock, Percent, DollarSign,
  Crown, RefreshCw, AlertTriangle
} from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import api from '../services/api';

interface Coupon {
  id: string;
  code: string;
  description?: string;
  discountType: 'FIXED' | 'PERCENTAGE';
  discountValue: number;
  minPurchase?: number;
  maxDiscount?: number;
  maxUses?: number;
  maxUsesPerUser: number;
  usedCount: number;
  isActive: boolean;
  isEliteOnly: boolean;
  isAutoGenerated: boolean;
  expiresAt?: string;
  rovexApproval: 'PENDING' | 'APPROVED' | 'REJECTED';
  rovexReviewNote?: string;
  createdAt: string;
  _count?: { usages: number };
}

interface AdminCouponsProps {
  showToast: (message: string, type: 'success' | 'error' | 'info') => void;
}

export default function AdminCoupons({ showToast }: AdminCouponsProps) {
  const { theme } = useAuth();
  const [coupons, setCoupons] = useState<Coupon[]>([]);
  const [loading, setLoading] = useState(true);
  const [showCreate, setShowCreate] = useState(false);
  const [filter, setFilter] = useState<'all' | 'active' | 'pending' | 'expired'>('all');

  // Create form
  const [code, setCode] = useState('');
  const [description, setDescription] = useState('');
  const [discountType, setDiscountType] = useState<'FIXED' | 'PERCENTAGE'>('FIXED');
  const [discountValue, setDiscountValue] = useState('');
  const [minPurchase, setMinPurchase] = useState('');
  const [maxDiscount, setMaxDiscount] = useState('');
  const [maxUses, setMaxUses] = useState('');
  const [isEliteOnly, setIsEliteOnly] = useState(false);
  const [expiresAt, setExpiresAt] = useState('');
  const [creating, setCreating] = useState(false);

  const cardBg = theme === 'light'
    ? 'bg-white/80 border-gray-200/60'
    : 'bg-white/[0.03] border-white/[0.08]';

  useEffect(() => {
    fetchCoupons();
  }, [filter]);

  const fetchCoupons = async () => {
    try {
      setLoading(true);
      const params = filter !== 'all' ? { status: filter } : {};
      const res = await api.get('/coupons/admin/list', { params });
      setCoupons(res.data);
    } catch (error) {
      console.error('Error fetching coupons:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleCreate = async () => {
    if (!code || !discountValue) {
      showToast('Código e valor são obrigatórios', 'error');
      return;
    }
    setCreating(true);
    try {
      await api.post('/coupons/admin/create', {
        code,
        description: description || undefined,
        discountType,
        discountValue: parseFloat(discountValue),
        minPurchase: minPurchase ? parseFloat(minPurchase) : undefined,
        maxDiscount: maxDiscount ? parseFloat(maxDiscount) : undefined,
        maxUses: maxUses ? parseInt(maxUses) : undefined,
        isEliteOnly,
        expiresAt: expiresAt || undefined,
      });
      showToast('Cupom criado! Aguardando aprovação da Rovex.', 'success');
      setShowCreate(false);
      resetForm();
      fetchCoupons();
    } catch (error: any) {
      showToast(error.response?.data?.error || 'Erro ao criar cupom', 'error');
    } finally {
      setCreating(false);
    }
  };

  const handleDelete = async (id: string) => {
    try {
      await api.delete(`/coupons/admin/${id}`);
      setCoupons(coupons.filter(c => c.id !== id));
      showToast('Cupom removido', 'success');
    } catch (error) {
      showToast('Erro ao remover cupom', 'error');
    }
  };

  const resetForm = () => {
    setCode('');
    setDescription('');
    setDiscountType('FIXED');
    setDiscountValue('');
    setMinPurchase('');
    setMaxDiscount('');
    setMaxUses('');
    setIsEliteOnly(false);
    setExpiresAt('');
  };

  const copyCode = (code: string) => {
    navigator.clipboard.writeText(code);
    showToast('Código copiado!', 'info');
  };

  const getApprovalBadge = (status: string) => {
    switch (status) {
      case 'APPROVED':
        return <span className="flex items-center gap-1 text-xs px-2 py-0.5 rounded-full bg-green-500/10 text-green-400"><CheckCircle className="w-3 h-3" /> Aprovado</span>;
      case 'PENDING':
        return <span className="flex items-center gap-1 text-xs px-2 py-0.5 rounded-full bg-yellow-500/10 text-yellow-400"><Clock className="w-3 h-3" /> Pendente</span>;
      case 'REJECTED':
        return <span className="flex items-center gap-1 text-xs px-2 py-0.5 rounded-full bg-red-500/10 text-red-400"><XCircle className="w-3 h-3" /> Rejeitado</span>;
      default:
        return null;
    }
  };

  const inputClass = theme === 'light'
    ? 'bg-white border-gray-200 text-gray-900 placeholder-gray-400 focus:ring-purple-500/30'
    : 'bg-white/5 border-white/10 text-white placeholder-gray-500 focus:ring-purple-500/30';

  return (
    <div className={`${cardBg} border backdrop-blur-2xl rounded-2xl p-6`}>
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <div className="p-2.5 rounded-xl bg-gradient-to-br from-purple-500/20 to-pink-500/20 border border-purple-500/10">
            <Tag className="w-5 h-5 text-purple-400" />
          </div>
          <div>
            <h3 className={`font-semibold ${theme === 'light' ? 'text-gray-900' : 'text-white'}`}>
              Sistema de Cupons
            </h3>
            <p className="text-xs text-gray-400">Gerenciar cupons de desconto da loja</p>
          </div>
        </div>
        <button
          onClick={() => setShowCreate(!showCreate)}
          className="flex items-center gap-1.5 px-3 py-2 bg-gradient-to-r from-purple-500/20 to-pink-500/20 border border-purple-500/20 rounded-xl text-purple-400 text-sm font-medium hover:from-purple-500/30 hover:to-pink-500/30 transition-all"
        >
          <Plus className="w-4 h-4" />
          Criar Cupom
        </button>
      </div>

      {/* Create Form */}
      <AnimatePresence>
        {showCreate && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            className="overflow-hidden mb-6"
          >
            <div className={`p-5 rounded-xl ${theme === 'light' ? 'bg-gray-50' : 'bg-white/[0.03]'} border ${theme === 'light' ? 'border-gray-200' : 'border-white/5'} space-y-4`}>
              <div className="flex items-center justify-between">
                <h4 className={`font-medium ${theme === 'light' ? 'text-gray-900' : 'text-white'}`}>Novo Cupom</h4>
                <div className="flex items-center gap-1.5 text-xs text-yellow-400">
                  <AlertTriangle className="w-3.5 h-3.5" />
                  Requer aprovação da Rovex
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-xs text-gray-400 mb-1 block">Código *</label>
                  <input
                    value={code}
                    onChange={(e) => setCode(e.target.value.toUpperCase())}
                    placeholder="EX: DESCONTO10"
                    className={`w-full px-3 py-2.5 rounded-xl border text-sm ${inputClass} focus:outline-none focus:ring-2`}
                  />
                </div>
                <div>
                  <label className="text-xs text-gray-400 mb-1 block">Tipo de Desconto</label>
                  <div className="flex gap-2">
                    <button
                      onClick={() => setDiscountType('FIXED')}
                      className={`flex-1 py-2.5 rounded-xl text-sm font-medium border transition-all ${discountType === 'FIXED'
                        ? 'bg-purple-500/10 border-purple-500/30 text-purple-400'
                        : `${theme === 'light' ? 'bg-white border-gray-200 text-gray-600' : 'bg-white/5 border-white/5 text-gray-400'}`
                        }`}
                    >
                      <DollarSign className="w-4 h-4 inline" /> Fixo
                    </button>
                    <button
                      onClick={() => setDiscountType('PERCENTAGE')}
                      className={`flex-1 py-2.5 rounded-xl text-sm font-medium border transition-all ${discountType === 'PERCENTAGE'
                        ? 'bg-purple-500/10 border-purple-500/30 text-purple-400'
                        : `${theme === 'light' ? 'bg-white border-gray-200 text-gray-600' : 'bg-white/5 border-white/5 text-gray-400'}`
                        }`}
                    >
                      <Percent className="w-4 h-4 inline" /> %
                    </button>
                  </div>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-xs text-gray-400 mb-1 block">
                    Valor * {discountType === 'FIXED' ? '(R$)' : '(%)'}
                  </label>
                  <input
                    type="number"
                    value={discountValue}
                    onChange={(e) => setDiscountValue(e.target.value)}
                    placeholder={discountType === 'FIXED' ? '10.00' : '15'}
                    className={`w-full px-3 py-2.5 rounded-xl border text-sm ${inputClass} focus:outline-none focus:ring-2`}
                  />
                </div>
                <div>
                  <label className="text-xs text-gray-400 mb-1 block">Compra mínima (R$)</label>
                  <input
                    type="number"
                    value={minPurchase}
                    onChange={(e) => setMinPurchase(e.target.value)}
                    placeholder="0.00"
                    className={`w-full px-3 py-2.5 rounded-xl border text-sm ${inputClass} focus:outline-none focus:ring-2`}
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-xs text-gray-400 mb-1 block">Máximo de usos</label>
                  <input
                    type="number"
                    value={maxUses}
                    onChange={(e) => setMaxUses(e.target.value)}
                    placeholder="Ilimitado"
                    className={`w-full px-3 py-2.5 rounded-xl border text-sm ${inputClass} focus:outline-none focus:ring-2`}
                  />
                </div>
                <div>
                  <label className="text-xs text-gray-400 mb-1 block">Expira em</label>
                  <input
                    type="date"
                    value={expiresAt}
                    onChange={(e) => setExpiresAt(e.target.value)}
                    className={`w-full px-3 py-2.5 rounded-xl border text-sm ${inputClass} focus:outline-none focus:ring-2`}
                  />
                </div>
              </div>

              <div>
                <label className="text-xs text-gray-400 mb-1 block">Descrição (opcional)</label>
                <input
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  placeholder="Desconto de boas-vindas"
                  className={`w-full px-3 py-2.5 rounded-xl border text-sm ${inputClass} focus:outline-none focus:ring-2`}
                />
              </div>

              <label className="flex items-center gap-3 cursor-pointer">
                <div className={`relative w-11 h-6 rounded-full transition-colors ${isEliteOnly ? 'bg-purple-500' : theme === 'light' ? 'bg-gray-300' : 'bg-white/10'}`}
                  onClick={() => setIsEliteOnly(!isEliteOnly)}>
                  <div className={`absolute top-0.5 left-0.5 w-5 h-5 bg-white rounded-full shadow transition-transform ${isEliteOnly ? 'translate-x-5' : ''}`} />
                </div>
                <div>
                  <span className={`text-sm font-medium ${theme === 'light' ? 'text-gray-700' : 'text-gray-300'}`}>
                    Exclusivo para Elite
                  </span>
                  <span className="text-xs text-gray-400 block">Apenas membros Elite poderão usar</span>
                </div>
              </label>

              <button
                onClick={handleCreate}
                disabled={creating || !code || !discountValue}
                className="w-full py-3 bg-gradient-to-r from-purple-500 to-pink-500 text-white rounded-xl font-medium hover:shadow-lg hover:shadow-purple-500/20 transition-all disabled:opacity-50 flex items-center justify-center gap-2"
              >
                {creating ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Plus className="w-4 h-4" />}
                {creating ? 'Criando...' : 'Criar Cupom'}
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Filter Tabs */}
      <div className="flex gap-1 mb-4">
        {[
          { key: 'all', label: 'Todos' },
          { key: 'active', label: 'Ativos' },
          { key: 'pending', label: 'Pendentes' },
          { key: 'expired', label: 'Expirados' },
        ].map(f => (
          <button
            key={f.key}
            onClick={() => setFilter(f.key as any)}
            className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${filter === f.key
              ? 'bg-purple-500/10 text-purple-400 border border-purple-500/20'
              : `${theme === 'light' ? 'text-gray-500 hover:bg-gray-100' : 'text-gray-400 hover:bg-white/5'}`
              }`}
          >
            {f.label}
          </button>
        ))}
      </div>

      {/* Coupons List */}
      <div className="space-y-2 max-h-[400px] overflow-y-auto pr-1">
        {loading ? (
          <div className="text-center py-6">
            <RefreshCw className="w-6 h-6 text-gray-400 animate-spin mx-auto" />
          </div>
        ) : coupons.length === 0 ? (
          <div className="text-center py-6">
            <Tag className="w-10 h-10 text-gray-500 mx-auto mb-2" />
            <p className="text-sm text-gray-400">Nenhum cupom encontrado</p>
          </div>
        ) : (
          coupons.map(coupon => (
            <motion.div
              key={coupon.id}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className={`p-3.5 rounded-xl ${theme === 'light' ? 'bg-gray-50' : 'bg-white/[0.03]'} border ${theme === 'light' ? 'border-gray-100' : 'border-white/5'}`}
            >
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => copyCode(coupon.code)}
                    className={`font-mono text-sm font-bold px-2.5 py-1 rounded-lg ${theme === 'light' ? 'bg-purple-50 text-purple-700' : 'bg-purple-500/10 text-purple-400'} hover:scale-105 transition-transform`}
                    title="Copiar código"
                  >
                    {coupon.code}
                  </button>
                  {coupon.isEliteOnly && (
                    <Crown className="w-4 h-4 text-amber-400" />
                  )}
                  {getApprovalBadge(coupon.rovexApproval)}
                </div>
                <div className="flex items-center gap-1">
                  {coupon.rovexApproval === 'PENDING' && (
                    <span className="text-[10px] text-amber-400/70 italic">Aguardando Rovex...</span>
                  )}
                  <button
                    onClick={() => handleDelete(coupon.id)}
                    className="p-1.5 rounded-lg hover:bg-red-500/10 text-red-400 transition-colors"
                    title="Excluir"
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
              </div>
              <div className="flex items-center gap-4 text-xs text-gray-400">
                <span>
                  {coupon.discountType === 'FIXED'
                    ? `R$ ${coupon.discountValue.toFixed(2)} off`
                    : `${coupon.discountValue}% off`}
                </span>
                <span>Usado: {coupon._count?.usages || coupon.usedCount}x</span>
                {coupon.maxUses && <span>Máximo: {coupon.maxUses}x</span>}
                {coupon.expiresAt && (
                  <span>Expira: {new Date(coupon.expiresAt).toLocaleDateString('pt-BR')}</span>
                )}
              </div>
              {coupon.description && (
                <p className="text-xs text-gray-500 mt-1">{coupon.description}</p>
              )}
            </motion.div>
          ))
        )}
      </div>
    </div>
  );
}
